services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-curso
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: t0m0m4t3!
      MYSQL_DATABASE: springcurso
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-mysql-net

networks:
  spring-mysql-net:
    driver: bridge

volumes:
  mysql_data: